/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import save.SaveFileReader;
import save.SaveFileWriter;
import simulation.Component;
import simulation.GUIConnection;
import simulation.Network;
import simulation.Point;
import simulation.Results;

/**
 *
 * @author Suhail
 */
public class NOCSimulatorGUI extends javax.swing.JFrame {

    /*
     * IMPORTANT:
     * ROW AND COLUMN TEXT IS REVERSED; METHODS RELATING TO ROWS ARE ACTUALLY
     * ABOUT COLUMNS AND VICE VERSA.
     * 
     */
    
    public static NOCSimulatorGUI current;
    
    public static GUIConnection connection;
    
    /**
     * Creates new form NOCSimulatorGUI
     */
    public NOCSimulatorGUI() {
        initComponents();
        current = this;
    }

    private void addFeedback(String feed){
        actionFeed.setText(actionFeed.getText() + "\n" + feed);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cycleNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        simulateButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clearSimulationButton = new javax.swing.JButton();
        resetComponentsButton = new javax.swing.JButton();
        saveSimulationButton = new javax.swing.JButton();
        BuildButton = new javax.swing.JButton();
        loadSimulationButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sizeValueRow = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        sizeValueCol = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        componentBox = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        rowLabel = new javax.swing.JLabel();
        colLabel = new javax.swing.JLabel();
        newCompName = new javax.swing.JTextField();
        renameButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        senderFrequency = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionFeed = new javax.swing.JTextArea();
        fromBox = new javax.swing.JComboBox();
        toBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOC Simulator");
        setResizable(false);

        resultsArea.setEditable(false);
        resultsArea.setColumns(20);
        resultsArea.setRows(5);
        jScrollPane1.setViewportView(resultsArea);

        jLabel1.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        jLabel1.setText("Simulation");

        cycleNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cycleNumberActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        jLabel2.setText("Number of Cycles:");

        simulateButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        simulateButton.setText("Simulate");
        simulateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(cycleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cycleNumber)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        jLabel3.setText("Options");

        clearSimulationButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        clearSimulationButton.setText("Clear Simulation");
        clearSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSimulationButtonActionPerformed(evt);
            }
        });

        resetComponentsButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        resetComponentsButton.setText("Reset Components");
        resetComponentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetComponentsButtonActionPerformed(evt);
            }
        });

        saveSimulationButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        saveSimulationButton.setText("Save Simulation");
        saveSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSimulationButtonActionPerformed(evt);
            }
        });

        BuildButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        BuildButton.setText("Build");
        BuildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildButtonActionPerformed(evt);
            }
        });

        loadSimulationButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        loadSimulationButton.setText("Load Simulation");
        loadSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSimulationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearSimulationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetComponentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(BuildButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadSimulationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveSimulationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuildButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(clearSimulationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetComponentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveSimulationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadSimulationButton))
        );

        jLabel5.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        jLabel5.setText("Simulation Properties");

        jLabel10.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        jLabel10.setText("Size:");

        sizeValueRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeValueRowActionPerformed(evt);
            }
        });

        jLabel16.setText("X");

        sizeValueCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeValueColActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sizeValueRow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sizeValueCol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeValueRow)
                    .addComponent(jLabel16)
                    .addComponent(sizeValueCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel9.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        jLabel9.setText("Component Properties");

        componentBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO NETWORK"}));
        componentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentBoxActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        nameLabel.setText("Name:");

        rowLabel.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        rowLabel.setText("Row: ");

        colLabel.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        colLabel.setText("Column: ");

        newCompName.setText("New Name");
        newCompName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCompNameActionPerformed(evt);
            }
        });

        renameButton.setText("Rename");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        infoButton.setText("NETWORK INFO");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(componentBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(newCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(renameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(colLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renameButton))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("DokChampa", 0, 16)); // NOI18N
        jLabel4.setText("Add and Remove Transmissions");

        jLabel6.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        jLabel6.setText("From:");

        jLabel7.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        jLabel7.setText("To:");

        jLabel8.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        jLabel8.setText("Frequency:");

        jLabel11.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        jLabel11.setText("Cycles");

        senderFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderFrequencyActionPerformed(evt);
            }
        });
        senderFrequency.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                senderFrequencyKeyTyped(evt);
            }
        });

        addButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        actionFeed.setColumns(20);
        actionFeed.setRows(5);
        jScrollPane2.setViewportView(actionFeed);

        fromBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO NETWORK" }));
        fromBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromBoxActionPerformed(evt);
            }
        });

        toBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO NETWORK"}));
        toBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("DokChampa", 0, 12)); // NOI18N
        jLabel12.setText("Every");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fromBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(senderFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(toBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senderFrequency)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cycleNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cycleNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cycleNumberActionPerformed

    private void clearSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSimulationButtonActionPerformed
        connection.clearSimulation();
        addFeedback("Simulation Cleared.");
    }//GEN-LAST:event_clearSimulationButtonActionPerformed

    private void simulateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateButtonActionPerformed
        System.out.println("this.cycleNumber.getText(): " + this.cycleNumber.getText());
        publishResults(connection.simulate(this.cycleNumber.getText()));
        try {
            addFeedback("Simulated " + Integer.parseInt(cycleNumber.getText()) + " cycles.");
        }
        catch (NumberFormatException e) {
            addFeedback("Error:\nCycle Number Invalid");
        }
        cycleNumber.setText("");
    }//GEN-LAST:event_simulateButtonActionPerformed

    private void resetComponentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetComponentsButtonActionPerformed
        connection.resetSimulation();
        addFeedback("Simulation Reset.");
    }//GEN-LAST:event_resetComponentsButtonActionPerformed

    private void saveSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSimulationButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int retval = fc.showSaveDialog(this);
        if (retval == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            try {
                SaveFileWriter.getInstance().writeToFile(file);
                /*try {
                SaveFileReader reader = SaveFileReader.getInstance();
                String contents = reader.readFile(file);
                reader.buildNetwork(contents);
                } catch (FileNotFoundException ex) {
                Logger.getLogger(NOCSimulatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NOCSimulatorGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            
        }
    }//GEN-LAST:event_saveSimulationButtonActionPerformed

    private void sizeValueRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeValueRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeValueRowActionPerformed

    private void senderFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderFrequencyActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            Component from, to;
            from = connection.getCompByName((String)fromBox.getSelectedItem());
            to = connection.getCompByName((String)toBox.getSelectedItem());
            if (from == null || to == null){
                return;
            }
            
            if (!connection.addSender(new Point(from.position.x,from.position.y), new Point(to.position.x,to.position.y), Integer.parseInt(this.senderFrequency.getText()))){
                //Error feed here...
                return;
            }
            addFeedback("Added Transmission.");
            senderFrequency.setText("");
        }
        catch (NumberFormatException nfe) {}
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        try {
            Component from, to;
            from = connection.getCompByName((String)fromBox.getSelectedItem());
            to = connection.getCompByName((String)toBox.getSelectedItem());
            if (from == null || to == null){
                return;
            }
            
            if (!connection.removeSender(new Point(from.position.x,from.position.y), new Point(to.position.x,to.position.y), Integer.parseInt(this.senderFrequency.getText()))){
                //Error feed here...
                return;
            }
            addFeedback("Removed Transmission.");
            senderFrequency.setText(""); 
        }
        catch (NumberFormatException nfe) {}
    }//GEN-LAST:event_removeButtonActionPerformed

    private void BuildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildButtonActionPerformed
        // TODO add your handling code here:
        connection.buildSimulator(this.sizeValueRow.getText(),this.sizeValueCol.getText());
        addFeedback("Built Simulation of size: " + this.sizeValueRow.getText() + "x" + this.sizeValueCol.getText());
        sizeValueRow.setText("");
        sizeValueCol.setText("");
    }//GEN-LAST:event_BuildButtonActionPerformed

    private void senderFrequencyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senderFrequencyKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_senderFrequencyKeyTyped

    private void sizeValueColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeValueColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeValueColActionPerformed

    private void loadSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSimulationButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int retval = fc.showOpenDialog(this);
        if (retval == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            try {
                SaveFileReader reader = SaveFileReader.getInstance();
                String contents = reader.readFile(file);
                reader.buildNetwork(contents);
                if (reader.errorFlag != 0){
                    connection.clearNetwork();
                    resultsArea.setText("");
                    addFeedback("Corrupt File. Simulation cleared.");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NOCSimulatorGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            
        }
    }//GEN-LAST:event_loadSimulationButtonActionPerformed

    private void fromBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromBoxActionPerformed

    private void toBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toBoxActionPerformed

    private void componentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentBoxActionPerformed
        connection.selectComponent((String)componentBox.getItemAt(componentBox.getSelectedIndex()));
        
        if (Component.getSelected() == null){
            return;
        }
        Component comp = Component.getSelected();
        rowLabel.setText("Row: "+ comp.position.x);
        colLabel.setText("Column: "+ comp.position.y);
        nameLabel.setText("Name: "+ comp.name);
        resultsArea.setText(comp.getInfo());
    }//GEN-LAST:event_componentBoxActionPerformed

    private void newCompNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCompNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCompNameActionPerformed

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        connection.updateComponentName(newCompName.getText());
    }//GEN-LAST:event_renameButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        if (Network.network != null){
            resultsArea.setText(Network.network.getNetworkInfo());
        }
        else {
            addFeedback("No network is defined!");
        }
    }//GEN-LAST:event_infoButtonActionPerformed

    
    private void publishResults(Results results){
        if (results == null){
            resultsArea.setText("Something went wrong!");
            return;
        }
        String res = "";
        for (int i = 0; i < connection.size.x; i++){
            if (i == 0){
                res += "ROW \\ COL\t";
                for (int marker = 0; marker < connection.size.y; marker++){
                    res += ("" + (marker) + "\t");
                }
                res += "\n\n";
            }
            res += ("" + i + "\t");
            for (int j =0; j < connection.size.y ; j++){
                
                
                res += ("" + i + "," + j + ": " + results.traffic[i][j] + "\t");
            }
            res += "\n\n";
        }
        resultsArea.setText(res);
        HeatMap map = new HeatMap(results);
        map.createAndShow();
    }
    
    public void updateBoxes(String[] names){
        fromBox.removeAllItems();
        toBox.removeAllItems();
        componentBox.removeAllItems();
      
        for (String name : names){
            fromBox.addItem(name);
            toBox.addItem(name);
            componentBox.addItem(name);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NOCSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NOCSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NOCSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NOCSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Initializing the connector to the backend */
        connection = new GUIConnection();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NOCSimulatorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuildButton;
    private javax.swing.JTextArea actionFeed;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearSimulationButton;
    private javax.swing.JLabel colLabel;
    private javax.swing.JComboBox componentBox;
    private javax.swing.JTextField cycleNumber;
    private javax.swing.JComboBox fromBox;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadSimulationButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newCompName;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton renameButton;
    private javax.swing.JButton resetComponentsButton;
    private javax.swing.JTextArea resultsArea;
    private javax.swing.JLabel rowLabel;
    private javax.swing.JButton saveSimulationButton;
    private javax.swing.JTextField senderFrequency;
    private javax.swing.JButton simulateButton;
    private javax.swing.JTextField sizeValueCol;
    private javax.swing.JTextField sizeValueRow;
    private javax.swing.JComboBox toBox;
    // End of variables declaration//GEN-END:variables
}
